// Generated by https://quicktype.io

import { ExpenseType } from "../enums/expense-types.enum";

export interface Expense {
	title: string;
	ccName: string;
	acquiredAt: string;
	creditCard: string;
	type: ExpenseType;
	amount: number;
	installments: number;
	firstPaymentDate: string;
	payments: string[];
	id: string;
}
