// Generated by https://quicktype.io

import { ExpenseType } from '../enums';
import { Payment } from './payments.interface';

export interface Expense {
	id: string;
	title: string;
	ccName: string;
	acquiredAt: string;
	creditCard: string;
	type: ExpenseType;
	amount: number;
	installments: number;
	firstPaymentDate: string;
	isDone: boolean;
	payments: Payment[];
}
