// Generated by https://quicktype.io

import { PaymentStatus } from "../enums/payment-status.enum";

export interface Payment {
	status: PaymentStatus;
	amount: number;
	noInstallment: number;
	month: number;
	year: number;
	expense: string;
	id: string;
}
